Remove "Indices and tables" section
osuosl/wiki pull request #154
Opened 2023-09-21 21:23 UTC by ArtofBugs

2023-09-21 21:24 UTC, osuosl-manatee commented
This PR has been automatically built and can be viewed here: https://wiki-154.staging.osuosl.org

2023-09-28 22:05 UTC, ramereth requested changes

2023-09-28 22:05 UTC, ramereth commented on source/gsoc/index.rst
> +.. _stay tuned: https://www.facebook.com/OSUOSL/
I'd rather we just keep it this and not link back to a Facebook page we don't
really maintain currently.

```suggestion
   participating in Google Summer of Code.
```

2023-10-03 17:58 UTC, osuosl-manatee commented
This PR has been automatically built and can be viewed here: https://wiki-154.staging.osuosl.org

2023-10-03 21:08 UTC, ramereth approved these changes

2023-10-03 21:08 UTC, merged