Add page to wiki to help people with IPQoS scp issue
osuosl/wiki pull request #57
Opened 2021-08-30 17:44 UTC by daviddjh

Adds a page to wiki explaining why speeds are so slow at times with scp, and how to fix it with either the ssh config file or the command line option.

2021-08-30 17:45 UTC, osuosl-manatee commented
This PR has been automatically built and can be viewed here: https://wiki-57.staging.osuosl.org

2021-08-30 19:12 UTC, ramereth requested changes

2021-08-30 19:12 UTC, ramereth commented on source/howtos/ssh_ip_qos_fix.rst
> +The Differentiated Services Code Point (DSCP_) field in an IP header is for
Can you please wrap these at 120 char?

2021-08-30 19:51 UTC, osuosl-manatee commented
This PR has been automatically built and can be viewed here: https://wiki-57.staging.osuosl.org

2021-08-31 16:24 UTC, ramereth commented on source/howtos/ssh_ip_qos_fix.rst
> +network, ``CS1`` packets are dropped very frequently, thus resulting in poor performance when SCPing.
We don't know if this is the case globally.
```suggestion
network, ``CS1`` packets might be dropped very frequently, thus resulting in poor performance when SCPing.
```

2021-08-31 18:29 UTC, osuosl-manatee commented
This PR has been automatically built and can be viewed here: https://wiki-57.staging.osuosl.org

2021-09-01 00:14 UTC, ramereth approved these changes

2021-09-01 00:14 UTC, merged